### ISSUE TITLE
"[adx @ 000001acdb3716c0] Encoder did not produce proper pts, making some up."

### ISSUE THREAD

**Issue by kTeo-0** [Firebow59/SofdecVideoTools#2]
Currently doing some tests and found out that most of the shorter videos can't be converted. Here's an example of what's happening along with the video i used in it:

[error.zip](https://github.com/Firebow59/SofdecVideoTools/files/11752113/error.zip)

awesome tool btw, it's making my job a LOT easier and the result is even better than before. Thank you so much for this!

**Comment by Firebow59** [comment]
I've released a new update that should fix the issue you were having. Let me know if it doesn't work for you.

**Comment by kTeo-0** [comment]
Awesome, it seems to be working perfectly now.
