### ISSUE TITLE
Sonic Mega Collection Plus Video Doesn't Play All The Way

### ISSUE THREAD

**Issue by MilesTailsFan2005** [Firebow59/SofdecVideoTools#5]
Hey.. I've been wanting to add Custom SFDs TO SMCP

They Work Kinda Just Randomly Cuts Out

https://www.youtube.com/watch?v=s8kI-7Gah5s

**Comment by Firebow59** [comment]
Hey there! I took a look into this today, and I can't seem to find any reason why this would happen. Is there any possibility that you could share the SFD file you made?
