### ISSUE TITLE
Unable to Create SFD

### ISSUE THREAD

**Issue by BoyleVoices** [Firebow59/SofdecVideoTools#6]
Hello,

I'm trying to adjust the audio in a particular SFD video in Sonic Adventure 2.  The SFD Extractor worked great and I was able to adjust the audio exactly how I wanted it, but when I run the SFD Creator, it gives me an error advising the SFD could not be created.  I'm not sure if this is a bug or if I'm doing something wrong.  If you can help me get this working, I'll be forever grateful!

![Capture](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/c79fde41-d1da-4a93-bbad-e53343a8dc0d)

**Comment by Firebow59** [comment]
Hey there!

Could you toggle show FFmpeg commands in the Extra Options menu, and then scroll through the output and see if there's any red text that appears? If there is, please send a screenshot if possible.

If no red error text appears, let me know, and I'll see if I can get a patch to improve the error system so that the exact problem can be determined as soon as I can.

Thanks!

**Comment by BoyleVoices** [comment]
Hello,

I toggled FFmpeg output and I don't see any red text, but there is a lot more information populating.  There is purple text, I'll send another screenshot here.  Hopefully this helps.

![ffmpeg screenshot](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/9d7a55c5-5ca7-4c61-92c4-657cc9118492)

Thank you.

**Comment by BoyleVoices** [comment]
Hoping this information is useful as well...I don't know what it means by setting a correct buffer size.

![Capture](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/b5233532-c2ba-4a8b-a6f8-79a663175f46)
![Capture2](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/2a30cef6-7e9b-4b2f-b55c-ba545c306037)

**Comment by BoyleVoices** [comment]
Even after eliminating OneDrive entirely, I'm still running into the same errors.  Here's the last thing it tells me when I attempted to run it just now: C:\Users\kyleb\OneDrive\Desktop\Edit is not recognized as an internal or external command, operable program or batch file.

I'm noticing that the path it lists does not match the output I selected.  The output I selected is C:/Users/kyleb/Desktop/Edit SA2 Cutscenes, so it has to be something else...

![recentexample](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/54285243-abd8-4d23-b721-84c26e1fc504)

Totally willing to pay you for your time if you're willing to maybe setup 10 minutes and maybe view my screen on Discord?

**Comment by Firebow59** [comment]
This definitely is an issue in the code based on that last error message still showing up. Based on the "Creating SFD" message that gets printed, I'm assuming its having an error finding sfdmux.exe. I've tried to add various extra print commands in this [modified EXE](https://github.com/Firebow59/SofdecVideoTools/files/14548670/SFDCreator_2.0.1_PATCH1.zip) to see what exactly why this is happening. Just replace the EXE in with the one you have currently, and toggle "Enable Extra Debug Info" in the extra options menu, and send a screenshot of what it says if possible.

**Comment by BoyleVoices** [comment]
Here's 3 screenshots of everything that it gives me after I run the file you provided.  Hopefully this information helps.

![screenshot1](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/a850402b-d22b-4ac2-a011-d8bdd26e2f45)

![screenshot2](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/92835d61-7f47-454f-bd9b-cd65f2c14b5f)

![screenshot3](https://github.com/Firebow59/SofdecVideoTools/assets/162655165/cde2995c-f375-4a62-96fe-e7535abad9cd)

**Comment by Firebow59** [comment]
The bug should be fixed now, let me know if it isn't!

**Comment by BoyleVoices** [comment]
You are a genius!!  Thank you for your assistance, it's working smoothly now.  Do you accept donations?
