### ISSUE TITLE
Suggestion: Merge `check_for_ffmpeg()` into one single .py

### ISSUE THREAD

**Issue by at-wr** [Firebow59/SofdecVideoTools#7]
I found out that the function `check_for_ffmpeg()` has been repeated in every Python script (except updater). Making one single change to the function and sync it manually must be painful.

So I guess maybe you can add a new Python file specifically for defining functions that might be reused?

Great project btw, I like it ; )

**Comment by Firebow59** [comment]
Great idea - I'll be sure to implement it in the next update!

Also, thank you for the compliment, I appreciate it!
