### ISSUE TITLE
Dragon Drive JP Gamecube SFD missing audio

### ISSUE THREAD

**Issue by RoundaboutSnake** [Firebow59/SofdecVideoTools#8]
As a test, I unpacked a SFD file from this game and put it back together without any augmentation. After doing this, the sound no longer plays.

**Comment by RoundaboutSnake** [comment]
To clarify, it works in the SFD player. It doesn't work in the Dolphin emulator. It is likely that the unpacking or repacking method is too imprecise because Dragon Drive streams audio from disc.

**Comment by Firebow59** [comment]
Hey there! I checked a couple SFDs from the game in a hex editor and discovered that they were made using a different type of V1 muxer (known as CRAFT) that isn't yet in SofdecVideoTools. It seems to handle audio differently compared to other V1 muxers, which likely is the source of why the audio isn't playing.

All I can recommend at this moment is trying to use the V1 (V1.07) or V1 (alt) muxers and see if one of them works, or waiting until the next update where the CRAFT muxer should hopefully be available as an option.

**Comment by RoundaboutSnake** [comment]
Hi! Thanks for responding! Well, I tried using the V1 and V1 alt, but it gave me an error in red when I did this. Would you like me to share it? 

I have fully subbed the video files and injected them into the game, but of course, they are silent in game. I was hoping you could figure something out in the future. Again, thanks for taking the time to look at it.

**Comment by Firebow59** [comment]
If you wouldn't mind sharing the error message it would be greatly appreciated!

Also, if you're alright waiting until later this week or next week, I can take a look into the CRAFT muxer and write up a quick patch/script for creating the SFDs with the CRAFT muxer.

**Comment by RoundaboutSnake** [comment]
"x.sfd could not created. Try creating the SFD again. If this occurs, it could be a problem with the input video file, or the audio files may not have been properly created."

I'm fine waiting because I'm really at the mercy of your schedule. Right now, I have subbed videos with no sound in the game, so that is how the translation patch is being distributed. All I can do is wait. Thank you again for taking time to look at this.

**Comment by Firebow59** [comment]
I was able to take a look into this today, hopefully [this](https://drive.google.com/file/d/1aXbq7ts6pDCfQkRIYYWS9EcgbacX-eK-/view?usp=sharing) should be able to create the SFDs for the game without any issues.

**Comment by RoundaboutSnake** [comment]
Thank you for looking into this. I was able to test it out with the opening song, and there seems to be a bug where the last few seconds of audio repeats / doesn't stop on time. When I watch the last seconds of the .wav file being encoded in the command prompt, it seems to be taking a really long time.

**Comment by Firebow59** [comment]
I am on Discord, my username on there is firebow59. Feel free to shoot me a message when you get the chance.
